services:
  app:
    build: .
    container_name: PawSy-app-alt
    ports:
      - "8085:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: PawSy-db-alt
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Pawsy_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3309:3306"
    volumes:
      - db_data_alt:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PawSyadmin-alt
    restart: always
    ports:
      - "8086:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data_alt:
